### ISSUE TITLE
Error: Unexpected token

### ISSUE THREAD

**Issue by decalage2** [DissectMalware/XLMMacroDeobfuscator#106]
Here is another Unexpected token error:
- Issue: https://github.com/decalage2/oletools/issues/741#issuecomment-1047703769
- Sample: https://bazaar.abuse.ch/sample/306433cdeddadf922a7849ab12431fbdb1f1f7f23dc4de1c2e378dcf9a05ca8a/

**Comment by DissectMalware** [comment]
Maybe related to [this issue](https://github.com/DissectMalware/XLMMacroDeobfuscator/issues/101)

**Comment by DissectMalware** [comment]
this issue is fixed (https://github.com/DissectMalware/XLMMacroDeobfuscator/commit/90a58f4a88676ee75db1581394b9503cd4f65e75)

![image](https://user-images.githubusercontent.com/9646319/167410429-24469b3f-ca5f-4fac-864d-fcda3b86f1d5.png)
