### ISSUE TITLE
Regression in recent commit causes crash

### ISSUE THREAD

**Issue by jhhcs** [DissectMalware/XLMMacroDeobfuscator#112]
In 90a58f4a88676ee75db1581394b9503cd4f65e75, code was added that causes XLMDeobfuscator to crash for some samples, see my comment at https://github.com/DissectMalware/XLMMacroDeobfuscator/commit/90a58f4a88676ee75db1581394b9503cd4f65e75#r79357256. An example for a file that can trigger this regression is the (malicious) sample with the following SHA-256 hash:
```
f272928566acb4bd59315337208ec3be1563864bcd4a40e39e3400715811aa8d
```

**Comment by huettenhain** [comment]
See the above PR for a fairly straightforward fix.

**Comment by DissectMalware** [comment]
Thank you for spotting the error and fixing it; the PR is merged

**Comment by huettenhain** [comment]
Sweet, and thank _you_ for an awesome tool!
