### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Rafiot** [DissectMalware/XLMMacroDeobfuscator#115]
It's not a terrible issue, but would you mind packaging a new release with the patched untangle version? Having the vulnerable version listed in projects makes dependabot complains.

**Comment by Rafiot** [comment]
hey, just bumping this one, sorry if it's annoying :/

**Comment by doomedraven** [comment]
we getting the same in CAPE sandbox

**Comment by DissectMalware** [comment]
I will do it today; sorry for the delay

**Comment by DissectMalware** [comment]
v0.2.7 is released and now accessible via PyPI

https://pypi.org/project/XLMMacroDeobfuscator/0.2.7/

**Comment by doomedraven** [comment]
thank you

**Comment by Rafiot** [comment]
\o/ thank you!
