### ISSUE TITLE
issues with a sample using semicolon and GET.CELL

### ISSUE THREAD

**Issue by decalage2** [DissectMalware/XLMMacroDeobfuscator#4]
Hi, I'm just starting to use your interpreter with some samples which trigger errors, and I'd like to better understand how to fix them:
Here is one sample I tried: https://app.any.run/tasks/c6b84e38-9355-4de1-bb15-5d76421a81e8/

The first error I got is due to semicolons, which are not yet in your Lark grammar:
```
lark.exceptions.UnexpectedCharacters: No terminal defined for ';' at line 1 col 21

=FORMULA(GET.CELL(19;D81)*31-GET.CELL(17;D81);M81)
                    ^

Expecting: {'CONCATOP', 'MULTIOP', 'R_PRA', 'CMPOP', 'ADDITIVEOP', 'COMMA'}
```
It looks like commas and semicolons are similar, so I just edited the Lark grammar like this:
```
COMMA: "," | ";"
```
Then it seemed to work, but I end up with the following output:
```
[Loading Cells]
[Starting Deobfuscation]
CELL:A79       , PartialEvaluation   , FORMULA("GET.CELL(19;D81)*31-GET.CELL(17;D81)",D2YWVQ5QJS!M81)
CELL:A80       , NotImplemented      , APP.MAXIMIZE()

Process Interruption:
CELL:A81       =FORMULA(CHAR(A1-M81)&CHAR(C4-M81)&CHAR(C6-M81)&CHAR(C7-M81)&CHAR(A6-M81)&CHAR(A7-M81)&CHAR(A8-M81)&CHAR(A10-M81)&CHAR(A11-M81)&CHAR(B8-M81)&CHAR(C33-M81)&CHAR(C34-M81)&CHAR(A15-M81)&CHAR(A17-M81)&CHAR(A18-M81)&CHAR(A19-M81)&CHAR(C25-M81)&CHAR(C27-M81)&CHAR(C28-M81)&CHAR(A24-M81)&CHAR(A25-M81)&CHAR(A26-M81)&CHAR(A28-M81)&CHAR(A20-M81)&CHAR(A21-M81)&CHAR(A22-M81)&CHAR(A32-M81)&CHAR(A34-M81)&CHAR(A35-M81)&CHAR(A36-M81)&CHAR(A37-M81)&CHAR(A39-M81)&CHAR(D44-M81)&CHAR(D45-M81)&CHAR(D46-M81)&CHAR(A43-M81)&CHAR(B37-M81)&CHAR(B39-M81)&CHAR(B40-M81)&CHAR(A48-M81);B79)
M81 is not populated, what should be its value?
Enter XLM macro:
Tip: CLOSE() or HALT() to exist
```
Does it mean that the formula in A79 is not fully parsed, and then it will not set the content of M81 properly?

**Comment by DissectMalware** [comment]
I will take a look into it. The semicolon seems out of place. I cannot create similar formula via excel.

![image](https://user-images.githubusercontent.com/9646319/80663220-5e7e0780-8a61-11ea-9afc-a1dedbd635fe.png)

Regarding the prompt, it means the value of M81 is needed to interpret the formula in cell A81 and this value has not been set yet (because CELL:A79 was partially evaluated, and the interpreter couldn't perform FORMULA operation)

**Comment by DissectMalware** [comment]
I analyzed the provided xls file. If seems  the formula contains comma (,) not semicolon (;). Not sure why you get semicolon on your side

 =FORMULA(GET.CELL(19,D81)*31-GET.CELL(17,D81),M81)

Extracted macros using -x switch
![image](https://user-images.githubusercontent.com/9646319/80666182-807b8800-8a69-11ea-8a54-38d7fe8fa4a6.png)

The interpreter cannot calc the formula as it does not know how to compute GET.CELL function as of now. 
![image](https://user-images.githubusercontent.com/9646319/80666339-eb2cc380-8a69-11ea-8405-062cc9bbc9ee.png)

**Comment by DissectMalware** [comment]
I think now I know why the arguments are sparated with semicolon not comma

Please go to Control Panel -> Region -> Additional Setting. Look at List Separator

![image](https://user-images.githubusercontent.com/9646319/80670653-7cedfe00-8a75-11ea-8267-1c8c3b11ddcf.png)

It seems the List Separator in your language profile is semicolon not comma

I changed the list separator with semicolon and rerun the code, then I got the same error that you reported.

![image](https://user-images.githubusercontent.com/9646319/80670767-cc342e80-8a75-11ea-85d9-8f3319298b93.png)

Not sure what would be the best strategy to fix this issue.

Excel seems to rely on List Separator

**Comment by decalage2** [comment]
You are right about the semicolon: it's because my OS is configured with French regional settings, and Excel transforms formulas accordingly, even if I configured the Excel UI to be in English (otherwise Excel would even translate the formulas to French keywords)... I guess that if the xls was parsed directly from Python (e.g. using xlrd or similar) instead of using Excel in the background, we would get the original formulas with commas.

**Comment by DissectMalware** [comment]
Fixed the issue for now.
XLSWrapper queries the excel (Application.International) to get the mappings for list separator, left bracket, and right bracket.

For the xls instance, you can use the following separator:
![image](https://user-images.githubusercontent.com/9646319/80731453-f10dbd80-8ad8-11ea-9d9b-20cc83801fdd.png)

Interestingly, the deobfuscated code cannot be executed on your machine, as the code assumes the list separator is comma, which is not valid; thus fails.

![image](https://user-images.githubusercontent.com/9646319/80733222-6a0e1480-8adb-11ea-8a52-3ab7218fc8f3.png)

**Comment by DissectMalware** [comment]
https://github.com/DissectMalware/XLMMacroDeobfuscator/blob/78fc5aa78ed2200392fc207f150c3b4c5eaa66cb/xls_wrapper.py#L26

https://github.com/DissectMalware/XLMMacroDeobfuscator/blob/78fc5aa78ed2200392fc207f150c3b4c5eaa66cb/deobfuscator.py#L56
