### ISSUE TITLE
can only concatenate str (not "int") to str

### ISSUE THREAD

**Issue by jcarndt** [DissectMalware/XLMMacroDeobfuscator#46]
There is an error when running this file on the deobfuscator: https://app.any.run/tasks/a03dbd65-7949-4570-8ebf-89c060244b46

Output to the screen says:

[Loading Cells]
can only concatenate str (not "int") to str

**Comment by DissectMalware** [comment]
I am working to fix this issue

**Comment by DissectMalware** [comment]
It is fixed. Please update both [xlrd2](https://github.com/DissectMalware/xlrd2) and XLMMacroDeobfuscator from Github

Deofuscated macro of the provided sample: https://pastebin.com/iAuhw8Dp
