### ISSUE TITLE
Import of win32comext.axscript.server.error breaks xlmdeobfuscator under Linux.

### ISSUE THREAD

**Issue by kirk-sayre-work** [DissectMalware/XLMMacroDeobfuscator#50]
Can line 16 in deobfuscator.py be wrapped in a try/except so that the standard Exception class is used under Linux?

**Comment by DissectMalware** [comment]
It was a mistake (the import was not necessary). I removed the line.

The mistake was introduced 3 hours ago

![image](https://user-images.githubusercontent.com/9646319/85460834-a86eff80-b571-11ea-8a67-3406d6fd4932.png)

**Comment by kirk-sayre-work** [comment]
Sweet, thanks!

Kirk Sayre
Dynamic Defense Engineering Team
