### ISSUE TITLE
Latest Macro breaks decoding

### ISSUE THREAD

**Issue by enzok** [DissectMalware/XLMMacroDeobfuscator#53]
MD5: 32be081e75cc5beb0ffbf7189325444e (can be D/L from VirusTotal)

This latest sample is no longer decoded.

**Comment by DissectMalware** [comment]
This bug is fixed in [https://github.com/DissectMalware/XLMMacroDeobfuscator/tree/version-2.0](https://github.com/DissectMalware/XLMMacroDeobfuscator/tree/version-2.0)

pastebin output: [https://pastebin.com/xEcvfZPS](https://pastebin.com/xEcvfZPS)
