### ISSUE TITLE
Object of type 'Tree' is not JSON serializable

### ISSUE THREAD

**Issue by 0ssigeno** [DissectMalware/XLMMacroDeobfuscator#56]
Hi, when executing ```xlmdeobfuscator --file comunicatoX_XXX.xls --password agenzia --export-json result.json``` the emulator 
prints:
```
Encrypted xls file
[Loading Cells]
auto_open: auto_open->H!$AG$29291
[Starting Deobfuscation]
[END of Deobfuscation]
[Dumping Json]
Error: unable to dump the result into the specified file
Object of type 'Tree' is not JSON serializable
[End of Dumping]
```
Any info?
Md5 sample: a09ce707bb8f0f6f687b2881ce8a3fc1
VT scan: https://www.virustotal.com/gui/file/a6eb350d57e07a6812c59bdf3d8df7c94b299256f14fffec31e16e3dda901f14/detection

**Comment by DissectMalware** [comment]
Fixed the bug. Update from the master.

![image](https://user-images.githubusercontent.com/9646319/94139472-b0239600-fe37-11ea-81e7-7e66d9e3c5d0.png)

[result.zip](https://github.com/DissectMalware/XLMMacroDeobfuscator/files/5275595/result.zip)

**Comment by 0ssigeno** [comment]
Thank you! That was fast!
