### ISSUE TITLE
Pending Transaction for11 Days now

### ISSUE THREAD

**Issue by Dianaxrp** [DissectMalware/XLMMacroDeobfuscator#70]
Hello

I just used MetaMask for the first time.
I am also on mac using chrome.

I Sent a transaction from hard wallet to Coinbase but it's days later and still has not cleared.

It was sent from my address:
0xE2c3FbfcE0D2Dc2149b095AC53f0b4357cD7AAB2
To this address:
0x21344b10b694964f624913caad97d33ddfc9f83b

Several days after my Coinbase accounts account on transfer is still empty.
when I clik on the View on the Block explorer ￼operation I have this error:
404 - File or directory not found.
Page not found
The requested path was not found on BlockScout

How can this happen?
Please help!
Thanks,
Diana

![image](https://user-images.githubusercontent.com/77314064/104315713-3835b600-5490-11eb-9e73-0705d51b1fc8.png)

**Comment by Dianaxrp** [comment]
Disregard Regard MetaMask sentence please. And read bello that part thank you .

**Comment by DissectMalware** [comment]
It seems you posted on a wrong repository. I am not sure how I can help.

**Comment by Dianaxrp** [comment]
Do you think Coinbase has the ability to fix or revers this?
