### ISSUE TITLE
Unexpected token Token('CMPOP', '=')

### ISSUE THREAD

**Issue by Beercow** [DissectMalware/XLMMacroDeobfuscator#73]
CELL:D87       , FullEvaluation      ,          DEFINE.NAME("tyilvtu",19)
CELL:D91       , FullEvaluation      ,  NEXT
CELL:D77       , FullEvaluation      ,  WHILE(AND(fhosr<vhVS)) -> [True]
CELL:D80       , FullEvaluation      ,          DEFINE.NAME("fhosr",20)
CELL:D84       , FullEvaluation      ,          SET.VALUE($D$93,"=T(CHAR(INT(ZnYWIcb)))=T(CHAR(INT(ZnYWIcb)))=T(CHAR(INT(ZnYWIcb)))=T(CHAR(INT(ZnYWIcb)))=T(CHAR(INT(ZnYWIcb)))=T(CHAR(INT(ZnYWIcb)))=T(CHAR(INT(ZnYWIcb)))=T(CHAR(INT(ZnYWIcb)))=T(CHAR(INT(ZnYWIcb)))=T(CHAR(INT(ZnYWIcb)))=T(CHAR(INT(ZnYWIcb)))=T(CHAR(INT(ZnYWIcb)))=T(CHAR(INT(ZnYWIcb)))=T(CHAR(INT(ZnYWIcb)))=T(CHAR(INT(ZnYWIcb)))=T(CHAR(INT(ZnYWIcb)))=T(CHAR(INT(ZnYWIcb)))=T(CHAR(INT(ZnYWIcb)))=T(CHAR(INT(ZnYWIcb)))=T(CHAR(INT(ZnYWIcb)))")
CELL:D87       , FullEvaluation      ,          DEFINE.NAME("tyilvtu",20)
CELL:D91       , FullEvaluation      ,  NEXT
CELL:D77       , FullEvaluation      ,  WHILE(AND(fhosr<vhVS)) -> [True]
CELL:D80       , FullEvaluation      ,          DEFINE.NAME("fhosr",21)
CELL:D84       , FullEvaluation      ,          SET.VALUE($D$93,"=T(CHAR(INT(ZnYWIcb)))=T(CHAR(INT(ZnYWIcb)))=T(CHAR(INT(ZnYWIcb)))=T(CHAR(INT(ZnYWIcb)))=T(CHAR(INT(ZnYWIcb)))=T(CHAR(INT(ZnYWIcb)))=T(CHAR(INT(ZnYWIcb)))=T(CHAR(INT(ZnYWIcb)))=T(CHAR(INT(ZnYWIcb)))=T(CHAR(INT(ZnYWIcb)))=T(CHAR(INT(ZnYWIcb)))=T(CHAR(INT(ZnYWIcb)))=T(CHAR(INT(ZnYWIcb)))=T(CHAR(INT(ZnYWIcb)))=T(CHAR(INT(ZnYWIcb)))=T(CHAR(INT(ZnYWIcb)))=T(CHAR(INT(ZnYWIcb)))=T(CHAR(INT(ZnYWIcb)))=T(CHAR(INT(ZnYWIcb)))=T(CHAR(INT(ZnYWIcb)))=T(CHAR(INT(ZnYWIcb)))")
CELL:D87       , FullEvaluation      ,          DEFINE.NAME("tyilvtu",21)
CELL:D91       , FullEvaluation      ,  NEXT
CELL:D77       , FullEvaluation      ,  WHILE(AND(fhosr<vhVS)) -> [False]
Error [deobfuscator.py:2277 parse_tree = self.xlm_parser.parse(formula)]: Unexpected token Token('CMPOP', '=') at line 1, column 45.
Expected one of:
        * LIST_SEPARATOR
        * R_PRA
        * $END

[Day of Month] 28

Files:

[END of Deobfuscation]
time elapsed: 0.32625532150268555

Hash of file: 07e6ece14527349fae6cb7d6a7300cc23d80a74fbde902d506a4ddc35dc96cc7

**Comment by DissectMalware** [comment]
It seems your code is not updated. Please update from [new-version](https://github.com/DissectMalware/XLMMacroDeobfuscator/tree/new_version) branch.

It had still another issue, which I fixed a few seconds ago

![image](https://user-images.githubusercontent.com/9646319/106191714-3b5fc000-6179-11eb-92a3-e2e1b82d0edb.png)

**Comment by DissectMalware** [comment]
Merged new-version branch with master. Update from master and it should work.

**Comment by Beercow** [comment]
Not sure what is going on on my end. It keeps running and never ends. Seems to be stuck in a loop.

**Comment by DissectMalware** [comment]
It took me 41 seconds to deobfuscate this sample, please give it some time 

![image](https://user-images.githubusercontent.com/9646319/106199424-736c0080-6183-11eb-8943-6c68a67d4ddc.png)

**Comment by DissectMalware** [comment]
Please also make sure that you update xlrd2

pip install -U https://github.com/DissectMalware/xlrd2/archive/master.zip --no-cache

**Comment by Beercow** [comment]
> Please also make sure that you update xlrd2
> 
> pip install -U https://github.com/DissectMalware/xlrd2/archive/master.zip --no-cache

That was the issue. Thanks. :-)
