### ISSUE TITLE
Cfdi

### ISSUE THREAD

**Issue by Dany181286** [DissectMalware/XLMMacroDeobfuscator#82]
<cfdi:Comprobante xmlns:nomina12="http://www.sat.gob.mx/nomina12" xmlns:cfdi="http://www.sat.gob.mx/cfd/3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Version="3.3" Folio="202000754362" Fecha="2020-11-18T13:23:50" Sello="bR7QazjotXLsXQ/rfqeE2uvbd9bq1yTBRLp5LWNGxMb7Cg3JJ1OD0Sv49QPm9DYua/I9M6BXDyPma8kmhYSBkELlA9tKntFQMnri+Ei1R2eN4sx0GbE+9itij9Nt/PbZCUQrDZib6y8Tm/UiWcNCDjOvo6nr15xR/4EAbAyaDMXzveEbeVqkQHqX7uc3jk6+q02sSlllOsnCkui1GYbpipBxRx3OwxkaqZubonbjRY9Iu1+q9eLW2HfdeO03tPzNDbI14Th2ee+r5DOAAaAUGjf8kNIEA1H4d3f14QjDx43iu4qQrorIUwhAWgOsgTlWuPLXT1r7ErsqndM9Rc7NjQ==" FormaPago="99" NoCertificado="00001000000407217270" Certificado="MIIGZTCCBE2gAwIBAgIUMDAwMDEwMDAwMDA0MDcyMTcyNzAwDQYJKoZIhvcNAQELBQAwggGyMTgwNgYDVQQDDC9BLkMuIGRlbCBTZXJ2aWNpbyBkZSBBZG1pbmlzdHJhY2nDs24gVHJpYnV0YXJpYTEvMC0GA1UECgwmU2VydmljaW8gZGUgQWRtaW5pc3RyYWNpw7NuIFRyaWJ1dGFyaWExODA2BgNVBAsML0FkbWluaXN0cmFjacOzbiBkZSBTZWd1cmlkYWQgZGUgbGEgSW5mb3JtYWNpw7NuMR8wHQYJKoZIhvcNAQkBFhBhY29kc0BzYXQuZ29iLm14MSYwJAYDVQQJDB1Bdi4gSGlkYWxnbyA3NywgQ29sLiBHdWVycmVybzEOMAwGA1UEEQwFMDYzMDAxCzAJBgNVBAYTAk1YMRkwFwYDVQQIDBBEaXN0cml0byBGZWRlcmFsMRQwEgYDVQQHDAtDdWF1aHTDqW1vYzEVMBMGA1UELRMMU0FUOTcwNzAxTk4zMV0wWwYJKoZIhvcNAQkCDE5SZXNwb25zYWJsZTogQWRtaW5pc3RyYWNpw7NuIENlbnRyYWwgZGUgU2VydmljaW9zIFRyaWJ1dGFyaW9zIGFsIENvbnRyaWJ1eWVudGUwHhcNMTcwODExMTk1MjExWhcNMjEwODExMTk1MjExWjCCAQQxKDAmBgNVBAMTH1NFQ1JFVEFSSUEgREUgREVTQVJST0xMTyBTT0NJQUwxKDAmBgNVBCkTH1NFQ1JFVEFSSUEgREUgREVTQVJST0xMTyBTT0NJQUwxKDAmBgNVBAoTH1NFQ1JFVEFSSUEgREUgREVTQVJST0xMTyBTT0NJQUwxJTAjBgNVBC0THFNEUzkyMDUyMkw3MSAvIE5JRVI1MDA4MjFGOTMxHjAcBgNVBAUTFSAvIE5JRVI1MDA4MjFIREZUTkQxOTE9MDsGA1UECxM0U0VDUkVUQVJJQSBERSBERVNBUlJPTExPIFNPQ0lBTCBTSU4gVElQTyBERSBTT0NJRURBRDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJGpqMdbBc7p6Zpjlp2dk8rXDiZpv0cZTZndHc20JFCDWiHCSS1/rSkimY9hY+TfrysWemXoWW3RrTqO+CnOFgY52/Pve67YJEx79hMvXPJk4DaypbvUxgoQZ38JC97Py7Is/a5z/4vOPQhNWZcf+SjxqiF4TH/Q7cJdIhuJtWvSbI6KporCsrY77+yCGKJU3VxvcvO+1iUGd0j4lWcfn0NikaUtEd1cR3g/umE0M18bos1uOc0hh6iovxHYv83miU0ybF7lymXkuoMG7/imEhArLmo58VlgG1ZMd96oWWhRRC8ymTXvV0v9t0rxHclA/faUPqgrRjQ5RnTYpZ6yO4UCAwEAAaMdMBswDAYDVR0TAQH/BAIwADALBgNVHQ8EBAMCBsAwDQYJKoZIhvcNAQELBQADggIBAK3hFBnRrO6tVnZ/NHnoweLcxvqD4C/AzDRKN24tUiHLFjH0RnsA3GLlR8OZrDe2Zx1geobkp/4Pb7P1guOQvIBy00XBfQId8s6n4RmmYPLBAJowMcPlNByWvpcnobP9wqLOKfacvip4BN82bnhxL+vvLij/fYa/7nhOoGB3a4Ep+WzRUpzrwC8s7Y1xxUuOjLjdj6b/Z7hemZiwEkH6Kd1eSnPraiZjpnnexYw154tcZISQ9RQPax4bYMa888WyDBHOaNAOj5GsyUBRBxO1FtHuSzmnmfImwVSiMHErslnS1GNhwXgFd+owTMlmiZe5kFeuR4osmeB80pleJ3bonCVoj29qmoxAenOA5I8WOKeHtv9V2nyP0kZnflaUAgLnT/LiPuDPSf6bXg9xjDDugWyA5B8Rq93Z35CUyah+/a1hJeULsE2IkjfCyfAoPXXWktddR9tLDDwJ3Cv+lziBnaA+t+UiEBvoR7fi349tUYaeokuV5LndPAHxCqBCrhnFerZ9ZAsOlvyg+BjNuXlNy2hotkrwDoBmVorEeAanjdpcKP1MBqXgsmNwjSZ3ZxguxVtdw+8FH7TCh/1cAQg2Gqw8XHkbBAxV4PICh+WMxz3E7EUVa2t8SfLm97F4Uu1J9UKM1D7P7Sx8gli5VrZ9hz/HM6OlatV7sBcXM+kdLCsn" SubTotal="3136.43" Descuento="404.43" Moneda="MXN" Total="2732.00" TipoDeComprobante="N" MetodoPago="PUE" LugarExpedicion="06600" xsi:schemaLocation="http://www.sat.gob.mx/cfd/3 http://sat.gob.mx/sitio_internet/cfd/3/cfdv33.xsd http://www.sat.gob.mx/nomina12 http://www.sat.gob.mx/sitio_internet/cfd/nomina/nomina12.xsd">
<cfdi:Emisor Rfc="SDS920522L71" Nombre="SECRETARIA DE DESARROLLO SOCIAL" RegimenFiscal="603"/>
<cfdi:Receptor Rfc="HELM791015VC6" Nombre="HERNANDEZ DE LUNA MARTIN" UsoCFDI="P01"/>
<cfdi:Conceptos>
<cfdi:Concepto ClaveProdServ="84111505" Cantidad="1" ClaveUnidad="ACT" Descripcion="Pago de nómina" ValorUnitario="3136.43" Importe="3136.43" Descuento="404.43"/>
</cfdi:Conceptos>
<cfdi:Complemento>
<nomina12:Nomina Version="1.2" TipoNomina="E" FechaPago="2020-11-18" FechaInicialPago="2020-11-30" FechaFinalPago="2020-11-30" NumDiasPagados="1" TotalPercepciones="3136.43" TotalDeducciones="404.43" TotalOtrosPagos="0">
<nomina12:Emisor RegistroPatronal="020090001"/>
<nomina12:Receptor Curp="HELM791015HASRNR02" NumSeguridadSocial="80197927256" FechaInicioRelLaboral="2019-01-01" Antigüedad="P1Y10M29D" TipoContrato="03" TipoJornada="01" TipoRegimen="02" NumEmpleado="92516" Puesto="ENLACE DE PRESTACION DE SERVICIOS A LA NACION" RiesgoPuesto="1" PeriodicidadPago="99" CuentaBancaria="127010001209488476" SalarioDiarioIntegrado="0" ClaveEntFed="DIF"/>
<nomina12:Percepciones TotalSueldos="3136.43" TotalGravado="3136.43" TotalExento="0">
<nomina12:Percepcion TipoPercepcion="002" Clave="024" Concepto="AGUINALDO COMPENSACION" ImporteGravado="2732.00" ImporteExento="0"/>
<nomina12:Percepcion TipoPercepcion="009" Clave="038" Concepto="CONTRAPARTIDA AGUINALDO COMPENSACION" ImporteGravado="404.43" ImporteExento="0"/>
</nomina12:Percepciones>
<nomina12:Deducciones TotalOtrasDeducciones="0" TotalImpuestosRetenidos="404.43">
<nomina12:Deduccion TipoDeduccion="002" Clave="001" Concepto="I S R AGUINALDO COMPENSACION" Importe="404.43"/>
</nomina12:Deducciones>
<nomina12:OtrosPagos>
<nomina12:OtroPago TipoOtroPago="002" Clave="0SE" Concepto="SUBSIDIO PARA EL EMPLEO" Importe="0.00">
<nomina12:SubsidioAlEmpleo SubsidioCausado="0.00"/>
</nomina12:OtroPago>
</nomina12:OtrosPagos>
</nomina12:Nomina>
<tfd:TimbreFiscalDigital xmlns:tfd="http://www.sat.gob.mx/TimbreFiscalDigital" xsi:schemaLocation="http://www.sat.gob.mx/TimbreFiscalDigital http://www.sat.gob.mx/sitio_internet/cfd/TimbreFiscalDigital/TimbreFiscalDigitalv11.xsd" Version="1.1" UUID="3757409B-8A90-4582-A726-096AF2BB8D44" FechaTimbrado="2020-11-18T14:28:37" RfcProvCertif="SAT970701NN3" SelloCFD="bR7QazjotXLsXQ/rfqeE2uvbd9bq1yTBRLp5LWNGxMb7Cg3JJ1OD0Sv49QPm9DYua/I9M6BXDyPma8kmhYSBkELlA9tKntFQMnri+Ei1R2eN4sx0GbE+9itij9Nt/PbZCUQrDZib6y8Tm/UiWcNCDjOvo6nr15xR/4EAbAyaDMXzveEbeVqkQHqX7uc3jk6+q02sSlllOsnCkui1GYbpipBxRx3OwxkaqZubonbjRY9Iu1+q9eLW2HfdeO03tPzNDbI14Th2ee+r5DOAAaAUGjf8kNIEA1H4d3f14QjDx43iu4qQrorIUwhAWgOsgTlWuPLXT1r7ErsqndM9Rc7NjQ==" NoCertificadoSAT="00001000000504465028" SelloSAT="iJCwjPkE3UJTwLRoeJypQqJGdeyKhtWPG5X5DuqK/CQveE5yyq8ldRBR/OBOc9geupqV/GdrWhhRnu2oQVSknpDW8/K+C9sQo2SlVZ0Dv+JoPUrthkLMB9lQTSqgkhPVDJ2hc/j8HcU+eGHbTLR4C0ZtFdYB0eFyeqZIoPsBgSM103lJBA9vstjzgnk7hojghxsETJ2ujSP4k3hfz5gdBxJjUS/lvUABgqArA6KYvNy25tD8I6w0YLRk6XBief98K0UXsOEpJio1UFUjwFIQE15SLoj1r/UnFW9595WrGk/VXH3BQnsh9SfuO+bZuhnsMr20qekkXpP5zkq3KSfAUA=="/>
</cfdi:Complemento>
</cfdi:Comprobante>

**Comment by Dany181286** [comment]
> <cfdi:Comprobante xmlns:nomina12="http://www.sat.gob.mx/nomina12" xmlns:cfdi="http://www.sat.gob.mx/cfd/3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Version="3.3" Folio="202000754362" Fecha="2020-11-18T13:23:50" Sello="bR7QazjotXLsXQ/rfqeE2uvbd9bq1yTBRLp5LWNGxMb7Cg3JJ1OD0Sv49QPm9DYua/I9M6BXDyPma8kmhYSBkELlA9tKntFQMnri+Ei1R2eN4sx0GbE+9itij9Nt/PbZCUQrDZib6y8Tm/UiWcNCDjOvo6nr15xR/4EAbAyaDMXzveEbeVqkQHqX7uc3jk6+q02sSlllOsnCkui1GYbpipBxRx3OwxkaqZubonbjRY9Iu1+q9eLW2HfdeO03tPzNDbI14Th2ee+r5DOAAaAUGjf8kNIEA1H4d3f14QjDx43iu4qQrorIUwhAWgOsgTlWuPLXT1r7ErsqndM9Rc7NjQ==" FormaPago="99" NoCertificado="00001000000407217270" Certificado="MIIGZTCCBE2gAwIBAgIUMDAwMDEwMDAwMDA0MDcyMTcyNzAwDQYJKoZIhvcNAQELBQAwggGyMTgwNgYDVQQDDC9BLkMuIGRlbCBTZXJ2aWNpbyBkZSBBZG1pbmlzdHJhY2nDs24gVHJpYnV0YXJpYTEvMC0GA1UECgwmU2VydmljaW8gZGUgQWRtaW5pc3RyYWNpw7NuIFRyaWJ1dGFyaWExODA2BgNVBAsML0FkbWluaXN0cmFjacOzbiBkZSBTZWd1cmlkYWQgZGUgbGEgSW5mb3JtYWNpw7NuMR8wHQYJKoZIhvcNAQkBFhBhY29kc0BzYXQuZ29iLm14MSYwJAYDVQQJDB1Bdi4gSGlkYWxnbyA3NywgQ29sLiBHdWVycmVybzEOMAwGA1UEEQwFMDYzMDAxCzAJBgNVBAYTAk1YMRkwFwYDVQQIDBBEaXN0cml0byBGZWRlcmFsMRQwEgYDVQQHDAtDdWF1aHTDqW1vYzEVMBMGA1UELRMMU0FUOTcwNzAxTk4zMV0wWwYJKoZIhvcNAQkCDE5SZXNwb25zYWJsZTogQWRtaW5pc3RyYWNpw7NuIENlbnRyYWwgZGUgU2VydmljaW9zIFRyaWJ1dGFyaW9zIGFsIENvbnRyaWJ1eWVudGUwHhcNMTcwODExMTk1MjExWhcNMjEwODExMTk1MjExWjCCAQQxKDAmBgNVBAMTH1NFQ1JFVEFSSUEgREUgREVTQVJST0xMTyBTT0NJQUwxKDAmBgNVBCkTH1NFQ1JFVEFSSUEgREUgREVTQVJST0xMTyBTT0NJQUwxKDAmBgNVBAoTH1NFQ1JFVEFSSUEgREUgREVTQVJST0xMTyBTT0NJQUwxJTAjBgNVBC0THFNEUzkyMDUyMkw3MSAvIE5JRVI1MDA4MjFGOTMxHjAcBgNVBAUTFSAvIE5JRVI1MDA4MjFIREZUTkQxOTE9MDsGA1UECxM0U0VDUkVUQVJJQSBERSBERVNBUlJPTExPIFNPQ0lBTCBTSU4gVElQTyBERSBTT0NJRURBRDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJGpqMdbBc7p6Zpjlp2dk8rXDiZpv0cZTZndHc20JFCDWiHCSS1/rSkimY9hY+TfrysWemXoWW3RrTqO+CnOFgY52/Pve67YJEx79hMvXPJk4DaypbvUxgoQZ38JC97Py7Is/a5z/4vOPQhNWZcf+SjxqiF4TH/Q7cJdIhuJtWvSbI6KporCsrY77+yCGKJU3VxvcvO+1iUGd0j4lWcfn0NikaUtEd1cR3g/umE0M18bos1uOc0hh6iovxHYv83miU0ybF7lymXkuoMG7/imEhArLmo58VlgG1ZMd96oWWhRRC8ymTXvV0v9t0rxHclA/faUPqgrRjQ5RnTYpZ6yO4UCAwEAAaMdMBswDAYDVR0TAQH/BAIwADALBgNVHQ8EBAMCBsAwDQYJKoZIhvcNAQELBQADggIBAK3hFBnRrO6tVnZ/NHnoweLcxvqD4C/AzDRKN24tUiHLFjH0RnsA3GLlR8OZrDe2Zx1geobkp/4Pb7P1guOQvIBy00XBfQId8s6n4RmmYPLBAJowMcPlNByWvpcnobP9wqLOKfacvip4BN82bnhxL+vvLij/fYa/7nhOoGB3a4Ep+WzRUpzrwC8s7Y1xxUuOjLjdj6b/Z7hemZiwEkH6Kd1eSnPraiZjpnnexYw154tcZISQ9RQPax4bYMa888WyDBHOaNAOj5GsyUBRBxO1FtHuSzmnmfImwVSiMHErslnS1GNhwXgFd+owTMlmiZe5kFeuR4osmeB80pleJ3bonCVoj29qmoxAenOA5I8WOKeHtv9V2nyP0kZnflaUAgLnT/LiPuDPSf6bXg9xjDDugWyA5B8Rq93Z35CUyah+/a1hJeULsE2IkjfCyfAoPXXWktddR9tLDDwJ3Cv+lziBnaA+t+UiEBvoR7fi349tUYaeokuV5LndPAHxCqBCrhnFerZ9ZAsOlvyg+BjNuXlNy2hotkrwDoBmVorEeAanjdpcKP1MBqXgsmNwjSZ3ZxguxVtdw+8FH7TCh/1cAQg2Gqw8XHkbBAxV4PICh+WMxz3E7EUVa2t8SfLm97F4Uu1J9UKM1D7P7Sx8gli5VrZ9hz/HM6OlatV7sBcXM+kdLCsn" SubTotal="3136.43" Descuento="404.43" Moneda="MXN" Total="2732.00" TipoDeComprobante="N" MetodoPago="PUE" LugarExpedicion="06600" xsi:schemaLocation="http://www.sat.gob.mx/cfd/3 http://sat.gob.mx/sitio_internet/cfd/3/cfdv33.xsd http://www.sat.gob.mx/nomina12 [http://www.sat.gob.mx/sitio_internet/cfd/nomina/nomina12.xsd">](http://www.sat.gob.mx/sitio_internet/cfd/nomina/nomina12.xsd%22%3E)
> <cfdi:Emisor Rfc="SDS920522L71" Nombre="SECRETARIA DE DESARROLLO SOCIAL" RegimenFiscal="603"/>
> <cfdi:Receptor Rfc="HELM791015VC6" Nombre="HERNANDEZ DE LUNA MARTIN" UsoCFDI="P01"/>
> cfdi:Conceptos
> <cfdi:Concepto ClaveProdServ="84111505" Cantidad="1" ClaveUnidad="ACT" Descripcion="Pago de nómina" ValorUnitario="3136.43" Importe="3136.43" Descuento="404.43"/>
> </cfdi:Conceptos>
> cfdi:Complemento
> <nomina12:Nomina Version="1.2" TipoNomina="E" FechaPago="2020-11-18" FechaInicialPago="2020-11-30" FechaFinalPago="2020-11-30" NumDiasPagados="1" TotalPercepciones="3136.43" TotalDeducciones="404.43" TotalOtrosPagos="0">
> <nomina12:Emisor RegistroPatronal="020090001"/>
> <nomina12:Receptor Curp="HELM791015HASRNR02" NumSeguridadSocial="80197927256" FechaInicioRelLaboral="2019-01-01" Antigüedad="P1Y10M29D" TipoContrato="03" TipoJornada="01" TipoRegimen="02" NumEmpleado="92516" Puesto="ENLACE DE PRESTACION DE SERVICIOS A LA NACION" RiesgoPuesto="1" PeriodicidadPago="99" CuentaBancaria="127010001209488476" SalarioDiarioIntegrado="0" ClaveEntFed="DIF"/>
> <nomina12:Percepciones TotalSueldos="3136.43" TotalGravado="3136.43" TotalExento="0">
> <nomina12:Percepcion TipoPercepcion="002" Clave="024" Concepto="AGUINALDO COMPENSACION" ImporteGravado="2732.00" ImporteExento="0"/>
> <nomina12:Percepcion TipoPercepcion="009" Clave="038" Concepto="CONTRAPARTIDA AGUINALDO COMPENSACION" ImporteGravado="404.43" ImporteExento="0"/>
> </nomina12:Percepciones>
> <nomina12:Deducciones TotalOtrasDeducciones="0" TotalImpuestosRetenidos="404.43">
> <nomina12:Deduccion TipoDeduccion="002" Clave="001" Concepto="I S R AGUINALDO COMPENSACION" Importe="404.43"/>
> </nomina12:Deducciones>
> nomina12:OtrosPagos
> <nomina12:OtroPago TipoOtroPago="002" Clave="0SE" Concepto="SUBSIDIO PARA EL EMPLEO" Importe="0.00">
> <nomina12:SubsidioAlEmpleo SubsidioCausado="0.00"/>
> </nomina12:OtroPago>
> </nomina12:OtrosPagos>
> </nomina12:Nomina>
> <tfd:TimbreFiscalDigital xmlns:tfd="http://www.sat.gob.mx/TimbreFiscalDigital" xsi:schemaLocation="http://www.sat.gob.mx/TimbreFiscalDigital http://www.sat.gob.mx/sitio_internet/cfd/TimbreFiscalDigital/TimbreFiscalDigitalv11.xsd" Version="1.1" UUID="3757409B-8A90-4582-A726-096AF2BB8D44" FechaTimbrado="2020-11-18T14:28:37" RfcProvCertif="SAT970701NN3" SelloCFD="bR7QazjotXLsXQ/rfqeE2uvbd9bq1yTBRLp5LWNGxMb7Cg3JJ1OD0Sv49QPm9DYua/I9M6BXDyPma8kmhYSBkELlA9tKntFQMnri+Ei1R2eN4sx0GbE+9itij9Nt/PbZCUQrDZib6y8Tm/UiWcNCDjOvo6nr15xR/4EAbAyaDMXzveEbeVqkQHqX7uc3jk6+q02sSlllOsnCkui1GYbpipBxRx3OwxkaqZubonbjRY9Iu1+q9eLW2HfdeO03tPzNDbI14Th2ee+r5DOAAaAUGjf8kNIEA1H4d3f14QjDx43iu4qQrorIUwhAWgOsgTlWuPLXT1r7ErsqndM9Rc7NjQ==" NoCertificadoSAT="00001000000504465028" SelloSAT="iJCwjPkE3UJTwLRoeJypQqJGdeyKhtWPG5X5DuqK/CQveE5yyq8ldRBR/OBOc9geupqV/GdrWhhRnu2oQVSknpDW8/K+C9sQo2SlVZ0Dv+JoPUrthkLMB9lQTSqgkhPVDJ2hc/j8HcU+eGHbTLR4C0ZtFdYB0eFyeqZIoPsBgSM103lJBA9vstjzgnk7hojghxsETJ2ujSP4k3hfz5gdBxJjUS/lvUABgqArA6KYvNy25tD8I6w0YLRk6XBief98K0UXsOEpJio1UFUjwFIQE15SLoj1r/UnFW9595WrGk/VXH3BQnsh9SfuO+bZuhnsMr20qekkXpP5zkq3KSfAUA=="/>
> </cfdi:Complemento>
> </cfdi:Comprobante>

Print

**Comment by DissectMalware** [comment]
What is this? Can you explain?
