### ISSUE TITLE
entry point not found on Trickbot/EtterSilent sample

### ISSUE THREAD

**Issue by decalage2** [DissectMalware/XLMMacroDeobfuscator#84]
The latest XLMdeobfuscator does not find the entry point in this sample:
https://app.any.run/tasks/bbadb211-fb6c-41e9-9c36-2484b9ea9db8/# (9b1c03b0cca23a94f2d6988c66eb0d246ec2648623765e83dbf20548ac874837)

**Comment by DissectMalware** [comment]
This is a bug in xlrd2 lib.

Check https://github.com/DissectMalware/xlrd2/issues/6

Update xlrd2 to resolve it:
pip install -U https://github.com/DissectMalware/xlrd2/archive/master.zip
