### ISSUE TITLE
'bool' object has no attribute 'strip'

### ISSUE THREAD

**Issue by FafnerKeyZee** [DissectMalware/XLMMacroDeobfuscator#88]
Hello,

With the new version I got the following error:
`Error [deobfuscator.py:2445 evaluation_result = self.evaluate_parse_tree(current_cell, parse_tree, interactive)]: 'bool' object has no attribute 'strip'`

Tested with this file:
md5:	 7c9fc3a33ebc52ceb0a00d6c7a76379a
sha1:	 b97a272ac6046237666e2fbf9c950057ffa17cc0
sha256:	 4ac794017dc5fcbb90b384a098e7d5b3132e22ffede45d353334de2f0111784b
sha512:	 bab695a8ccc1224f40a18fe45dca10188ebeb87739eb835af47d03dbbf0c810a84847e79bf55c12935b67b4f8d118061cf331d64d2de535ae0ea9ab4042f05c2

Best regards,

**Comment by DissectMalware** [comment]
This bug is fixed in the last commit (3128c35ebce0cf3ed0ea6b0efad252d4d2e8467a). Please check.

![image](https://user-images.githubusercontent.com/9646319/121938812-225b4400-cd01-11eb-95e1-846767de25df.png)

**Comment by FafnerKeyZee** [comment]
Yep working :)
Thanks
